import pytest
from moto import mock_ec2, mock_sts

from cloudwanderer.models import ServiceResourceType
from cloudwanderer.urn import PartialUrn


@pytest.fixture
def s3_cleanup_actions():
    return [
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="af-south-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-northeast-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-northeast-2",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-northeast-3",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-south-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-southeast-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ap-southeast-2",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="ca-central-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-central-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-north-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-south-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-west-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-west-2",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="eu-west-3",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="sa-east-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-east-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-east-2",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-west-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-west-2",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-gov-east-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-gov-west-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="cn-north-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="cn-northwest-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        ),
    ]


@mock_sts
@mock_ec2
def test_get_resource_discovery_actions(aws_interface, s3_cleanup_actions):
    result = aws_interface.get_resource_discovery_actions(
        regions=["us-east-1"], service_resource_types=[ServiceResourceType(service="s3", resource_type="bucket")]
    )[0]

    assert result.get_urns == [
        PartialUrn(
            cloud_name="aws",
            account_id="123456789012",
            region="us-east-1",
            service="s3",
            resource_type="bucket",
            resource_id_parts=[],
        )
    ]
    for action in s3_cleanup_actions:
        assert action in result.delete_urns
